---
title: "Analysis of Initial JS message content (ENTRES-709)"
author: "Brendon Kaufman"
date: "2/2/2022"
output:
  html_document: 
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(googlesheets4)

coded_data_df <- read_csv("coded_data_df.csv") 

coded_data_df_mod <- coded_data_df %>%
  mutate(across(contains("flag"),
                .fns = function(.x) case_when(.x == "x" ~ TRUE,
                                              TRUE ~ FALSE))) %>%
  rowwise() %>%
  mutate(is_coded = sum(c_across(starts_with("flag"))) > 0) %>% 
  ungroup() %>%
  filter(is_coded) %>% # get rid of rows that don't have any columns coded
  select( # get rid of rows with all NAs
    where(
      ~sum(!is.na(.x)) > 0
    ))

```


```{r manipulate-data, fig.width = 14, fig.height= 6}

coded_data_analysis_df <- coded_data_df_mod %>%
  summarise(across(contains("flag"), .fns = function(.x) round(mean(.x), 2))) %>%
  pivot_longer(cols = contains("flag"), names_to = "tag", values_to = "proportion_of_messages") %>%
  mutate(tag_plain_text = case_when(tag == "flag_ui" ~ "UI",
                                    tag == "flag_customer_service" ~ "Customer Service",
                                    tag == "flag_buttons" ~ "Buttons"))

```

```{r plot-data}


ggplot(coded_data_analysis_df) +
  geom_col(aes(x = reorder(tag_plain_text, proportion_of_messages), y = proportion_of_messages),
           fill = "#237EA3") +
  geom_text(aes(x = tag_plain_text, y = proportion_of_messages, label = proportion_of_messages),
            nudge_y = 0.15,
            size = 8) +
  labs(x = "", y = "Proportion of comments",
       title = "Proportion of comments with theme",
       subtitle = paste0("Comments can have multiple tags (n = ",
                        nrow(coded_data_analysis_df),
                        ")")) +
  coord_flip() +
  theme(plot.title = element_text(margin = margin(0,0,20,0),
                                  size = 16),
        axis.text.x = element_blank(),
        plot.subtitle = element_text(size = 14)) 


```
